### ISSUE TITLE
Build error with static files (css) in ./public

### ISSUE THREAD

**Issue by bdombro** [TylorS/snowpack-plugin-hash#11]
TL;DR
I get a build error when I added some static JS/CSS to my public folder, namely Leaflet.js.

I created a barebones repo to demonstrate at https://github.com/bdombro/tmp-preact-snowpack-barebones. It's literally the create-snowpack-app base template with this plugin and added JS/CSS to the public folder.

I wonder if we could add an allowList and denyList option to this plugin? Because I don't mind if some files get hashed and some don't, and it would be a nice way to workaround future bugs.

Build output:
```

> build
> snowpack build

[snowpack] ! building source files...
[snowpack] ✔ build complete [0.03s]
[snowpack] ! building dependencies...
[snowpack] ✔ dependencies ready! [0.19s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.01s]
[snowpack] ! writing build to disk...
[snowpack] ! optimizing build...
falling back to enhanced-resolve #default#VML
/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:293
			const error = new Error("Can't " + message);
			              ^

Error: Can't resolve '#default#VML' in '/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/build/leaflet'
    at finishWithoutResolve (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:27:1)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:87:43
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:28:1)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/ConditionalPlugin.js:53:42
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/enhanced-resolve/lib/ImportsFieldPlugin.js:65:13
    at Hook.eval [as callAsync] (eval at create (/Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:7:1) {
  details: ''
}
npm ERR! code 1
npm ERR! path /Users/bdombrowski/Dev/_projects/benevolenttech/react-stack-router/preact-snowpack
npm ERR! command failed
npm ERR! command sh -c snowpack build

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/bdombrowski/.npm/_logs/2021-02-24T14_46_52_082Z-debug.log

```

**Comment by TylorS** [comment]
Hey @bdombro sorry you ran into some issues. Many thanks for the reproductive repo, I'll dig into this and see what I can find!

Regarding an allow/block list... that does seem like a very reasonable option for circumnavigating issues that have yet to be fixed. Have you had any other thoughts about a solution since?

**Comment by TylorS** [comment]
Hey @bdombro I pulled down your repo and add the latest plugin and I encountered no issues. Would you be able to try out the latest version and see if it works for you as well?

<img width="830" alt="Screen Shot 2021-04-01 at 6 20 04 PM" src="https://user-images.githubusercontent.com/6282473/113359992-e4ac6900-9316-11eb-9e5a-dbb8ad552668.png">

**Comment by sy1vain** [comment]
@bdombro I think I ran into the same problem today. But could not reproduce with your repo. This plugin is also not added, so that might be the reason why @TylorS can't reproduce.

For me it tripped over a favicon. My guess is that it has to do with the order that files get moved to the build folder. I added my static files to the snowpack mount option instead of just have them hang around in my src folder and that solved it.

**Comment by teleclimber** [comment]
I think I'm experiencing the same. In my case it can't find a hand-coded service worker that is in `/public`.

```
[snowpack-plugin-hash] ◼ [JS] Finding dependencies /Users/ollie/Documents/Code/Leftovers/app/frontend/dist/main.js...
falling back to enhanced-resolve ./sw.js
(node:19062) UnhandledPromiseRejectionWarning: Error: Can't resolve './sw.js' in '/Users/ollie/Documents/Code/Leftovers/app/frontend/dist'
    at finishWithoutResolve (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:293:18)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:362:15
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:16:1)
    at /Users/ollie/Documents/Code/Leftovers/frontend/node_modules/enhanced-resolve/lib/Resolver.js:410:5
    at eval (eval at create (/Users/ollie/Documents/Code/Leftovers/frontend/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

Main.ts:
```ts
import { createApp } from 'vue';
import App from './App.vue';
import router from './router';

import './assets/tailwind.css';

navigator.serviceWorker.register("/sw.js");

import dayjs from 'dayjs';
import relativeTime from 'dayjs/plugin/relativeTime';
dayjs.extend(relativeTime);

createApp(App).use(router).mount('#app');
```

I tried using `"/sw.js"`, `"sw.js"`, `"./sw.js"`, all fail.

And yes, there is a "sw.js" at the root of the build directory :)

I'm on 0.16.

Thanks!

----
Update: this may not be related to above issue at all. I can't get this plugin to find my service worker no matter where I put the sw (public or src). I'll try to come up with a repro and open an other issue.
