### ISSUE TITLE
Error: Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by francislavoie** [TylorS/snowpack-plugin-hash#4]
:thinking: 

```
$ snowpack build --watch

Error: Cannot find module 'fs/promises'
Require stack:
- ./node_modules/snowpack-plugin-hash/lib/appendImportMapToAssetManifest.js
- ./node_modules/snowpack-plugin-hash/lib/index.js
- ./node_modules/snowpack/lib/index.js
- ./node_modules/snowpack/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (./node_modules/snowpack-plugin-hash/lib/appendImportMapToAssetManifest.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (./node_modules/snowpack-plugin-hash/lib/index.js:11:42)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
```

**Comment by francislavoie** [comment]
Ah, I was on node v12.18.3

Updated to v14.15.4 and I get further now.
