### ISSUE TITLE
Viewport meta tag content breaks build

### ISSUE THREAD

**Issue by bongofury** [TylorS/snowpack-plugin-hash#9]
Hello, thanks for making this project available!

### Env

node v14.15.4
snowpack v3.0.10
snowpack-plugin-hash v0.12.0

### Description

I have the following _viewport_ meta tag in my _index.html_ head:
```html
<meta name="viewport" content="width=device-width, initial-scale=1.0">
```

This is breaking the build during the optimization phase, see logs below.
It seems that the _content_ attribute is recognized as a dependency import.

```
> snowpack build

[snowpack] ! building source files...
[snowpack] ✔ build complete [0.41s]
[snowpack] ! building dependencies...
[snowpack] ✔ dependencies ready! [1.81s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.01s]
[snowpack] ! writing build to disk...
[snowpack] ! optimizing build...
[snowpack-plugin-hash] ℹ Hashing Directory [path_to_project]/build...
[snowpack-plugin-hash] ℹ Rewriting Hashes...
[snowpack-plugin-hash] ℹ Remapping any source-map URLs...
[snowpack-plugin-hash] ℹ Generating Asset Manifest...
[snowpack] ✔ optimize complete [3.00s]
[snowpack] ▶ Build Complete!



~/__priv-projects/my-app master* 7s
❯ npm run build

> my-app@0.1.0 build [path_to_project]
> snowpack build

[snowpack] ! building source files...
[snowpack] ✔ build complete [0.43s]
[snowpack] ! building dependencies...
[snowpack] ✔ dependencies ready! [1.85s]
[snowpack] ! verifying build...
[snowpack] ✔ verification complete [0.01s]
[snowpack] ! writing build to disk...
[snowpack] ! optimizing build...
[snowpack-plugin-hash] ℹ Hashing Directory [path_to_project]/build...
(node:1962) UnhandledPromiseRejectionWarning: Error: Cannot find module 'width=device-width, initial-scale=1.0' from '[path_to_project]/build'
    at Function.resolveSync [as sync] ([path_to_project]/node_modules/resolve/lib/sync.js:90:15)
    at Object.resolvePackage ([path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/plugins/resolvePackage.js:10:30)
    at [path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/plugins/html.js:115:47
    at Array.map (<anonymous>)
    at [path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/plugins/html.js:96:14
    at [path_to_project]/node_modules/fp-ts/lib/Tree.js:340:77
    at [path_to_project]/node_modules/fp-ts/lib/Tree.js:327:13
    at Object.pipe ([path_to_project]/node_modules/fp-ts/lib/function.js:188:20)
    at [path_to_project]/node_modules/fp-ts/lib/Tree.js:330:24
    at Object.pipe ([path_to_project]/node_modules/fp-ts/lib/function.js:188:20)
    at [path_to_project]/node_modules/fp-ts/lib/Tree.js:330:24
    at Array.flatMap (<anonymous>)
    at findDependencies ([path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/plugins/html.js:79:10)
    at Object.<anonymous> ([path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/plugins/html.js:67:30)
    at Generator.next (<anonymous>)
    at Object.<anonymous> ([path_to_project]/node_modules/@typed/content-hash/lib/content-hashes/infrastructure/createReadFilePath.js:12:48)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1962) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1962) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by bongofury** [comment]
Oh, got it, the problem should be related to this piece of code https://github.com/TylorS/typed-content-hash/blob/29fa80838f725c2850775f9f0f0814185e54da37/src/content-hashes/infrastructure/plugins/html.ts#L135 .

Maybe I'll fix it later ;)

**Comment by bongofury** [comment]
I changed my viewport meta tag as following and the problem has gone.

```diff
-  <meta name="viewport" content="width=device-width, initial-scale=1.0">
+  <meta name="viewport" content="width=device-width, initial-scale=1">
```

Extname check returns `.0` if `width=device-width, initial-scale=1.0` is passed, see here https://github.com/TylorS/typed-content-hash/blob/29fa80838f725c2850775f9f0f0814185e54da37/src/content-hashes/infrastructure/plugins/html.ts#L161 .

Maybe that check is a little bit fragile, don't know if we should consider it a bug ang get it fixed.

**Comment by TylorS** [comment]
Hey @bongofury many thanks for opening this issues and the PR to typed-content-hash. I've added a response over there and I've opened another PR with a maybe alternative fix that also considers that `extname` being a bit fragile in that exact spot

**Comment by TylorS** [comment]
@bongofury I merged your PR over there, since it did seem like the right call to just remove things. v0.13.1 here has been released just to bump up the required version with the fix. Thanks for all your help! 

Feel free to re-open this issue if it is still affecting you 😄
